 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on https://172.26.4.75:5000/ (Press CTRL+C to quit)
146.75.187.19 - - [18/Jun/2021 08:29:05] "POST /process HTTP/1.1" 400 -
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on https://172.26.4.75:5000/ (Press CTRL+C to quit)
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on https://172.26.4.75:5000/ (Press CTRL+C to quit)
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20210618 08:31:00.792965 12952 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
app.py:29: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  src = cv2.imdecode(np.fromstring(request.files['file'].read(), np.uint8), cv2.IMREAD_UNCHANGED)
221.163.49.12 - - [18/Jun/2021 08:31:01] "POST /process HTTP/1.1" 200 -
146.75.187.20 - - [18/Jun/2021 08:31:29] "POST /process HTTP/1.1" 400 -
146.75.187.20 - - [18/Jun/2021 08:31:47] "POST /process HTTP/1.1" 400 -
W20210618 08:32:07.881309 12957 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
[2021-06-18 08:32:08,065] ERROR in app: Exception on /process [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 30, in process
    dst = correct.correct(src)
  File "/home/ubuntu/insta-shot/server/correct.py", line 14, in correct
    results = pose.process(img)
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solutions/pose.py", line 205, in process
    results = super().process(input_data={'image': image})
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 309, in process
    packet=self._make_packet(input_stream_type,
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 486, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/packet_creator.py", line 146, in create_image_frame
    return _packet_creator._create_image_frame_from_pixel_data(
TypeError: Cannot cast array data from dtype('uint16') to dtype('uint8') according to the rule 'safe'
110.70.57.178 - - [18/Jun/2021 08:32:08] "POST /process HTTP/1.1" 500 -
W20210618 08:32:14.020769 12959 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [18/Jun/2021 08:32:14] "POST /process HTTP/1.1" 200 -
W20210618 08:32:50.300981 12962 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [18/Jun/2021 08:32:50] "POST /process HTTP/1.1" 200 -
W20210618 08:35:00.598243 12964 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
[2021-06-18 08:35:00,689] ERROR in app: Exception on /process [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 30, in process
    dst = correct.correct(src)
  File "/home/ubuntu/insta-shot/server/correct.py", line 14, in correct
    results = pose.process(img)
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solutions/pose.py", line 205, in process
    results = super().process(input_data={'image': image})
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 309, in process
    packet=self._make_packet(input_stream_type,
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 486, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/packet_creator.py", line 146, in create_image_frame
    return _packet_creator._create_image_frame_from_pixel_data(
TypeError: Cannot cast array data from dtype('uint16') to dtype('uint8') according to the rule 'safe'
146.75.187.20 - - [18/Jun/2021 08:35:00] "POST /process HTTP/1.1" 500 -
W20210618 08:46:04.297909 12979 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [18/Jun/2021 08:46:04] "POST /process HTTP/1.1" 200 -
W20210618 09:07:22.911339 12986 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
146.75.187.21 - - [18/Jun/2021 09:07:23] "POST /process HTTP/1.1" 200 -
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on https://172.26.4.75:5000/ (Press CTRL+C to quit)
Exception ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on https://172.26.4.75:5000/ (Press CTRL+C to quit)
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on https://172.26.4.75:5000/ (Press CTRL+C to quit)
WARNING: Logging before InitGoogleLogging() is written to STDERR
W20210618 09:30:47.605302 13976 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
app.py:29: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  src = cv2.imdecode(np.fromstring(request.files['file'].read(), np.uint8), cv2.IMREAD_UNCHANGED)
175.198.82.73 - - [18/Jun/2021 09:30:47] "POST /process HTTP/1.1" 200 -
167.248.133.53 - - [18/Jun/2021 13:42:03] "GET / HTTP/1.1" 200 -
167.248.133.53 - - [18/Jun/2021 13:42:04] "GET / HTTP/1.1" 200 -
W20210618 21:03:02.680615 17310 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
[2021-06-18 21:03:02,871] ERROR in app: Exception on /process [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 30, in process
    dst = correct.correct(src)
  File "/home/ubuntu/insta-shot/server/correct.py", line 14, in correct
    results = pose.process(img)
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solutions/pose.py", line 205, in process
    results = super().process(input_data={'image': image})
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 309, in process
    packet=self._make_packet(input_stream_type,
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 486, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/packet_creator.py", line 146, in create_image_frame
    return _packet_creator._create_image_frame_from_pixel_data(
TypeError: Cannot cast array data from dtype('uint16') to dtype('uint8') according to the rule 'safe'
146.75.187.18 - - [18/Jun/2021 21:03:02] "POST /process HTTP/1.1" 500 -
W20210618 21:40:40.355345 18306 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
104.28.4.78 - - [18/Jun/2021 21:40:40] "POST /process HTTP/1.1" 200 -
W20210618 21:40:54.183974 18316 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
104.28.4.77 - - [18/Jun/2021 21:40:54] "POST /process HTTP/1.1" 200 -
W20210618 21:41:05.110795 18322 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
104.28.4.78 - - [18/Jun/2021 21:41:05] "POST /process HTTP/1.1" 200 -
W20210618 21:41:13.018059 18324 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
104.28.4.77 - - [18/Jun/2021 21:41:13] "POST /process HTTP/1.1" 200 -
W20210619 00:27:56.207134 19048 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
104.28.4.78 - - [19/Jun/2021 00:27:56] "POST /process HTTP/1.1" 200 -
W20210619 01:02:39.885898 19378 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
104.28.4.78 - - [19/Jun/2021 01:02:40] "POST /process HTTP/1.1" 200 -
W20210619 01:34:56.719867 19459 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:34:56] "POST /process HTTP/1.1" 200 -
W20210619 01:43:37.472046 19510 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 01:43:37] "POST /process HTTP/1.1" 200 -
W20210619 01:45:39.634747 19516 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:45:39] "POST /process HTTP/1.1" 200 -
W20210619 01:46:14.283608 19519 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:46:14] "POST /process HTTP/1.1" 200 -
W20210619 01:47:34.638657 19522 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:47:34] "POST /process HTTP/1.1" 200 -
W20210619 01:51:30.314630 19531 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 01:51:30] "POST /process HTTP/1.1" 200 -
W20210619 01:51:41.950723 19533 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 01:51:42] "POST /process HTTP/1.1" 200 -
W20210619 01:51:44.755014 19535 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:51:44] "POST /process HTTP/1.1" 200 -
W20210619 01:51:57.687961 19537 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:51:57] "POST /process HTTP/1.1" 200 -
W20210619 01:52:16.254519 19540 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:52:16] "POST /process HTTP/1.1" 200 -
W20210619 01:53:16.583096 19568 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:53:16] "POST /process HTTP/1.1" 200 -
W20210619 01:53:42.299161 19570 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:53:42] "POST /process HTTP/1.1" 200 -
W20210619 01:54:32.527549 19573 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 01:54:32] "POST /process HTTP/1.1" 200 -
W20210619 01:54:57.302377 19575 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 01:54:57] "POST /process HTTP/1.1" 200 -
W20210619 01:55:09.781236 19578 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 01:55:09] "POST /process HTTP/1.1" 200 -
W20210619 01:55:18.356552 19580 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 01:55:18] "POST /process HTTP/1.1" 200 -
W20210619 01:55:39.194447 19582 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
[2021-06-19 01:55:39,288] ERROR in app: Exception on /process [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 30, in process
    dst = correct.correct(src)
  File "/home/ubuntu/insta-shot/server/correct.py", line 14, in correct
    results = pose.process(img)
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solutions/pose.py", line 205, in process
    results = super().process(input_data={'image': image})
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 309, in process
    packet=self._make_packet(input_stream_type,
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 486, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/packet_creator.py", line 146, in create_image_frame
    return _packet_creator._create_image_frame_from_pixel_data(
TypeError: Cannot cast array data from dtype('uint16') to dtype('uint8') according to the rule 'safe'
110.70.57.178 - - [19/Jun/2021 01:55:39] "POST /process HTTP/1.1" 500 -
W20210619 01:55:41.774279 19584 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:55:42] "POST /process HTTP/1.1" 200 -
W20210619 01:59:24.044549 19591 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 01:59:24] "POST /process HTTP/1.1" 200 -
W20210619 02:01:19.255648 19595 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 02:01:19] "POST /process HTTP/1.1" 200 -
W20210619 02:01:36.232966 19597 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 02:01:36] "POST /process HTTP/1.1" 200 -
W20210619 02:02:04.986086 19599 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 02:02:05] "POST /process HTTP/1.1" 200 -
W20210619 02:02:16.670961 19602 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
110.70.57.178 - - [19/Jun/2021 02:02:16] "POST /process HTTP/1.1" 200 -
110.70.57.178 - - [19/Jun/2021 02:03:02] "POST /process HTTP/1.1" 400 -
W20210619 02:03:16.986608 19606 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
[2021-06-19 02:03:17,069] ERROR in app: Exception on /process [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 30, in process
    dst = correct.correct(src)
  File "/home/ubuntu/insta-shot/server/correct.py", line 14, in correct
    results = pose.process(img)
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solutions/pose.py", line 205, in process
    results = super().process(input_data={'image': image})
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 309, in process
    packet=self._make_packet(input_stream_type,
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/solution_base.py", line 486, in _make_packet
    return getattr(packet_creator, 'create_' + packet_data_type.value)(
  File "/usr/local/lib/python3.8/dist-packages/mediapipe/python/packet_creator.py", line 146, in create_image_frame
    return _packet_creator._create_image_frame_from_pixel_data(
TypeError: Cannot cast array data from dtype('uint16') to dtype('uint8') according to the rule 'safe'
110.70.57.178 - - [19/Jun/2021 02:03:17] "POST /process HTTP/1.1" 500 -
W20210619 02:05:55.412773 19623 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/pose_detection/pose_detection.tflite
221.163.49.12 - - [19/Jun/2021 02:05:55] "POST /process HTTP/1.1" 200 -
